### ISSUE TITLE
Packaging of 21-cm cosmological simulation

### ISSUE THREAD

**Issue by radiosky-abhik** [kernsuite/kernsuite.github.io#1]
Hi Gijs,
            Can you please package these 21-cm simulations.

1. 21cmFAST : https://github.com/andreimesinger/21cmFAST

2. Simfast21 : https://github.com/mariogrs/Simfast21

With Thanks,
  Abhik

**Comment by gijzelaerr** [comment]
i will have a look

the right place to report this is here https://github.com/kernsuite/packaging/issues/21

this is the kernsuite website, i'm not sure how you ended up here...
